apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-server.fullname" . }}-nginx-deployment
  labels:
  {{- include "nginx-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginxDeployment.replicas }}
  selector:
    matchLabels:
      app: nginx
    {{- include "nginx-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: nginx
      {{- include "nginx-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nginxDeployment.nginx.image.repository }}:{{ .Values.nginxDeployment.nginx.image.tag
          | default .Chart.AppVersion }}
        name: nginx
        ports:
        - containerPort: 80
        resources: {}